// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbIwcINFWL4kQN-mpZbd4YPBbIDOWKz7M',
    appId: '1:930286164303:web:b2889b6150dc3072734d3a',
    messagingSenderId: '930286164303',
    projectId: 'calling-app-651d3',
    authDomain: 'calling-app-651d3.firebaseapp.com',
    storageBucket: 'calling-app-651d3.appspot.com',
    measurementId: 'G-Y71PFWELW4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHNH5Q4PvmAUGBrMy4CL2ceJltRJgw9PA',
    appId: '1:930286164303:android:6ad8414c96debfaf734d3a',
    messagingSenderId: '930286164303',
    projectId: 'calling-app-651d3',
    storageBucket: 'calling-app-651d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACwSDzmRoRApNRe08IWb1is4OyqFcoWa0',
    appId: '1:930286164303:ios:c2e6d3d701094285734d3a',
    messagingSenderId: '930286164303',
    projectId: 'calling-app-651d3',
    storageBucket: 'calling-app-651d3.appspot.com',
    iosClientId: '930286164303-vptptcpf46ge1bi5s12r7kr5nifbdai3.apps.googleusercontent.com',
    iosBundleId: 'com.example.callingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACwSDzmRoRApNRe08IWb1is4OyqFcoWa0',
    appId: '1:930286164303:ios:ca54900dd593bd9d734d3a',
    messagingSenderId: '930286164303',
    projectId: 'calling-app-651d3',
    storageBucket: 'calling-app-651d3.appspot.com',
    iosClientId: '930286164303-4e7ap19o7vleo1331un9tbrt9putdep5.apps.googleusercontent.com',
    iosBundleId: 'com.example.callingApp.RunnerTests',
  );
}
